/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include <stdint.h>
typedef volatile unsigned int vint32_t;
//Register addresses
//RCC
#define RCC_BASE    0x40021000
#define RCC_APB2ENR *((volatile uint32_t *)(RCC_BASE+0x18))
#define RCC_IOPAEN  (1<<2)

//GPIO
#define PorTA_BASE  0x40010800
#define GPIO_ODR    *((volatile uint32_t *)(PorTA_BASE+0x0c))
#define GPIO_CRH    *((volatile uint32_t *)(PorTA_BASE+0x04))
#define GPIO_CRL    *((volatile uint32_t *)(PorTA_BASE+0x00))

//EXTI
#define EXTI_BASE    0x40010400
#define EXTI_IMR    *((volatile uint32_t *)(EXTI_BASE +0x0))
#define EXTI_RTSR    *((volatile uint32_t *)(EXTI_BASE +0x08))
#define EXTI_PR   *((volatile uint32_t *)(EXTI_BASE +0x14))


//AFIO
#define AFIO_BASE  0x40010000
#define AFIO_EXTICR1   *((volatile uint32_t *)(AFIO_BASE +0x08))

//NVIC
#define NVIC_BASE    0xE000E100
#define NVIC_EXTIE0  *((volatile uint32_t *)(NVIC_BASE +0x0))

void clock_init()
{
	//enable GPIOA clock
	RCC_APB2ENR |= RCC_IOPAEN ;
	//enable AFIO clock
	RCC_APB2ENR |= (1<<0);
}

void GPIO_init()
{
	//pin 13 port A output
	GPIO_CRH &=0xFF0FFFFF;
	GPIO_CRH |=0x00200000;

	//pin 0 port A input floating input
	GPIO_CRL |= (1<<2);
}
int main(void)
{
	clock_init();
	GPIO_init();

	//EXTI0 configration to port A0
	AFIO_EXTICR1 =0;
	//enable rising trigger
	EXTI_RTSR |= (1<<0);

//enable EXTI LINE 0(MASK1)
	EXTI_IMR |= (1<<0);

	//enable NVIC IRQ 6<<>>EXT0
	NVIC_EXTIE0 |= (1<<6);

	while(1);

	return 0;
}
void EXTI0_IRQHandler(void)
{
	//IRQ is happend EXTI0 >>> PORTA Pin 0 _|- rising edge
	//toggle led pinA 13
	GPIO_ODR ^= (1<<13);

	//clear pending request for line 0
	EXTI_PR |= (1<<0);

}
