/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
//   terminal1-----------> USART1 : MC1 :(SPI1:Master)--------->(SPI2 Slave):MCU2 :USART2------>Terminal2

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_ACT_AS_Master
#define MCU_ACT_AS_Slave

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include"Stm32_F103C6_USART_driver.h"
#include"Stm32_F103C6_SPI_driver.h"
#include "lcd.h"
#include "keypad.h"

unsigned char ch ;
void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void SPI1_IRQ_Callback(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_ACT_AS_Slave
	if(irq_src.RXNE)
	{
		ch=0xf;
		MCAL_SPI_TX_RX(SPI1,&ch, disable);
		MCAL_UART_SendData(USART1, &ch,enable);
	}
#endif



}
void M_UART_IRQ_Callback(void)
{
#ifdef MCU_ACT_AS_Master

	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);

	//send to SPI
	MCAL_GPIO_WritePin(GPIOA,GPIO_PIN_4, 0); //enable SS
	MCAL_SPI_TX_RX(SPI1, &ch, enable);
	MCAL_GPIO_WritePin(GPIOA,GPIO_PIN_4, 1);
#endif
}

int main(void)
{
	GPIO_PinConfig_t pincfg;
	UART_Config uartCFG ;

	clock_init();

	//===============================UART INIT=========
	//PA9 TX
	//PA10 RX
	//PA11 CTS
	//PA12 RTS
	uartCFG.BaudRate = UART_BaudRate_115200;
	uartCFG.HwFlowCtl =UART_HwFlowCtl_NONE;
	uartCFG.Parity = UART_Parity_NONE;
	uartCFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
	uartCFG.P_IRQ_Callback = M_UART_IRQ_Callback;
	uartCFG.Payload_Length = UART_Payload_8B ;
	uartCFG.USART_Mode = UART_Mode_TX_RX;
	uartCFG.StopBits = UART_StopBits_1 ;

	MCAL_UART_INIT(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1) ;

	//==================================SPI INIT ==========
	//PA4 :SPI1_NSS
	//PA5 :SPI1_SCK
	//PA6 :SPI1_MISO
	//PA7 :SPI1_MOSI
	SPI_Config SPI1CFG;

	//Common configuration
	SPI1CFG.CLKPhase = SPI_CLKPhase_2ndEDGE_first_data_capture_edge;
	SPI1CFG.CLKPolarity = SPI_CLKPolarity_High_when_idle;
	SPI1CFG.Data_Size = SPI_Data_Size_8BIT;
	SPI1CFG.frame_format= SPI_frame_format_MSB_transmitted_first;
	//assume by default pclk2 = 8MHZ
	SPI1CFG.SPI_BAUDRATEPrescaler = SPI_BAUDRATEPrescaler_8;
	SPI1CFG.Communication_Mode = SPI_Communication_Mode_2LINES;

#ifdef  MCU_ACT_AS_Master

	SPI1CFG.Device_Mode = SPI_Device_Mode_Master ;
	SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_NONE ;
	SPI1CFG.NSS = SPI_NSS_Soft_NSSInternalSoft_set; //the only master on bus
	SPI1CFG.P_IRQ_CallBack = NULL ;


	//configure SS on PA4 BY GPIO Output PP
	pincfg.GPIO_PinNumber = GPIO_PIN_4;
	pincfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	pincfg.GPIO_output_speed = GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOA,&pincfg);

	//Force the ss high idle mode
	MCAL_GPIO_WritePin(GPIOA,GPIO_PIN_4, 1);

#endif



#ifdef MCU_ACT_AS_Slave

	SPI1CFG.Device_Mode = SPI_Device_Mode_Slave ;
	SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_RXNEIE ;
	SPI1CFG.NSS = SPI_NSS_Hard_Slave;
	SPI1CFG.P_IRQ_CallBack = SPI1_IRQ_Callback;

#endif

	MCAL_SPI_INIT(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);
	while(1)
	{

	}













	return 0;
}
