/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "lcd.h"
#include "keypad.h"

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void clock_init()
{
	//enable GPIOA clock
	RCC_GPIOA_CLK_EN();
	//enable GPIOB clock
	RCC_GPIOB_CLK_EN() ;
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg;

	PinCfg.GPIO_PinNumber = GPIO_PIN_9;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_10;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_11;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_12;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//============================

	//PA13 input HighZ Floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_14;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//PB13 (output PUSH pull Mode)
	PinCfg.GPIO_PinNumber = GPIO_PIN_15;
	PinCfg.GPIO_Mode = GPIO_Mode_OUTPUT_PP;
	PinCfg.GPIO_output_speed= GPIO_output_speed_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}

void my_wait(int x)
{
	unsigned int i,j;
	for(i=0 ; i<x ; i++);
	for(j=0 ;j<255 ; j++);
}

int main(void)
{
	unsigned char key_pressed;

	clock_init();

	LCD_INIT();

	LCD_WRITE_STRING("Hey there");
	my_wait(500);
	LCD_clear_screen();
	GPIO_init();

	unsigned char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	unsigned char DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	for (unsigned char i = 0; i < 11; i++) {
		LCD_WRITE_CHAR(LCD_DISPLAY[i]);
		MCAL_GPIO_WritePORT(GPIOB, DISPLAY[i] << 9); /* write data on to the LED port */
		my_wait(100);
		/* wait for 1 second */
	}
	LCD_clear_screen();
	Keypad_init();
	LCD_WRITE_STRING("Keypad is ready");
	my_wait(100);
	LCD_clear_screen();

	while (1) {

		key_pressed = Keypad_getkey();
		switch (key_pressed) {
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_CHAR(key_pressed);
			break;
		}
	}

	//		//PA1 connected with external PUR
	//
	//		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 ) // press
	//		{
	//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1) ;
	//			while(  MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 ) ;//single press
	//
	//		}
	//
	//		//PA13 connected with external PDR
	//		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1 ) // MULTIpress
	//		{
	//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13) ;;
	//
	//		}
	//	my_wait(1);



	return 0;
}
