/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "lcd.h"
#include "keypad.h"

enum CpuAcessLevel {
	privileged ,
	unprivileged
};

void SWITCH_CPU_AcessLevel(enum CpuAcessLevel  level)
{
	switch (level)
	{
	case privileged:
		//Clear Bit 0 in CONTROL Resister
		__asm("mrs r3 , CONTROL \n\t"
				"lsr r3 , r3 ,#0x1 \n\t"
				"lsl r3 , r3 ,#0x1 \n\t"
				"msr CONTROL , r3");
		break;
		break;

	case unprivileged:
		//Set Bit 0 in CONTROL Resister
		__asm("mrs r3 , CONTROL \n\t"
				"orr r3 , r3 ,#0x1 \n\t"
				"msr CONTROL , r3");
		break;
	}
}
void my_wait(int x)
{
	unsigned int i,j;
	for(i=0 ; i<x ; i++);
	for(j=0 ;j<255 ; j++);
}
unsigned int IRQ_flag ;

unsigned int CPU_Control_Register = 0;
unsigned int CPU_IPSR_Register = 0;

void EXTI9_Callback(void)
{
	IRQ_flag =1;
	SWITCH_CPU_AcessLevel(privileged);
}




int main(void)
{

	//Enable clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_Pinconfig_t EXTI_CFG ;
	EXTI_CFG.EXTI_PIN = EXTI9PB9 ;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING ;
	EXTI_CFG.P_IRQ_Callback = EXTI9_Callback ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable ;
	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);
	IRQ_flag =1;

	SWITCH_CPU_AcessLevel(unprivileged);


	while(1)
	{
		if(IRQ_flag)
		{
			LCD_clear_screen();
			IRQ_flag =0;
		}

	}













	return 0;
}
