/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "core_cm3.h"
//#include "stm32f103x6.h"
//#include "Stm32_F103C6_gpio_driver.h"
//#include "Stm32_F103C6_EXTI_driver.h"
//#include "lcd.h"
//#include "keypad.h"

#include "scheduler.h"



Task_ref Task1 , Task2 , Task3 ,Task4;
unsigned char task1Led , task2Led ,task3Led,task4Led;
Mutex_ref MUTEX1 ,MUTEX2 ;
unsigned char Payload[3]= {1,2,3};
unsigned char Payload2[3]= {1,2,3};
void task1()
{
	static int count = 0 ;
	while(1)
	{
		task1Led ^= 1 ;
		count ++;
		if (count == 100)
		{
			MYRTOS_AcquireMutex(&MUTEX1, &Task1);
			MYRTOS_ActivateTask(&Task4);
			MYRTOS_AcquireMutex(&MUTEX2, &Task1);

		}
		if (count == 200)
		{
			count = 0 ;
			MYRTOS_ReleaseMutex(&MUTEX1);
		}
	}
}

void task2()
{

	static int count = 0 ;
	while(1)
	{
		task2Led ^= 1 ;
		count ++;
		if (count == 100)
		{
			MYRTOS_ActivateTask(&Task3);

		}
		if (count == 200)
		{
			count = 0 ;
			MYRTOS_TerminateTask(&Task2);
		}
	}
}

void task3()
{

	static int count = 0 ;
	while(1)
	{
		task3Led ^= 1 ;
		count ++;
		if (count == 100)
		{
			MYRTOS_ActivateTask(&Task4);
		}
		if (count == 200)
		{
			count = 0 ;
			MYRTOS_TerminateTask(&Task3);
		}
	}
}
void task4()
{

	static int count = 0 ;
	while(1)
	{
		task4Led ^= 1 ;
		count ++;

		if (count == 3)
		{
			MYRTOS_AcquireMutex(&MUTEX2, &Task4);
		MYRTOS_AcquireMutex(&MUTEX1, &Task4);
		}
		if (count == 200)
		{
			count = 0 ;
			MYRTOS_ReleaseMutex(&MUTEX1);
			MYRTOS_TerminateTask(&Task4);

		}
	}


}
int main(void)
{
	MYRTOS_errorID error;
	HW_init();

	if (MYRTOS_init() != NoError)
		while(1);

	MUTEX1.PayloadSize =3;
	MUTEX1.Ppayload = Payload ;
	strcpy(MUTEX1.MutexName ,"mutex1_shared_T1_T4");

	MUTEX2.PayloadSize =3;
	MUTEX2.Ppayload = Payload2 ;
	strcpy(MUTEX2.MutexName ,"mutex2_shared_T4_T1");

	Task1.Stack_Size = 1024 ;
	Task1.p_TaskEntry = task1 ;
	Task1.priority = 4 ;
	strcpy(Task1.TaskName , "task1");

	Task2.Stack_Size = 1024 ;
	Task2.p_TaskEntry = task2 ;
	Task2.priority = 3 ;
	strcpy(Task2.TaskName , "task2");

	Task3.Stack_Size = 1024 ;
	Task3.p_TaskEntry = task3 ;
	Task3.priority = 2;
	strcpy(Task3.TaskName , "task3");

	Task4.Stack_Size = 1024 ;
	Task4.p_TaskEntry = task4 ;
	Task4.priority = 1;
	strcpy(Task4.TaskName , "task4");

	error += MYRTOS_CreateTask(&Task1) ;
	error += MYRTOS_CreateTask(&Task2) ;
	error += MYRTOS_CreateTask(&Task3) ;
	error += MYRTOS_CreateTask(&Task4) ;

	MYRTOS_ActivateTask(&Task1);




	MYRTOS_STARTOS();

	while(1)
	{

	}




	return 0;
}
